ca_directory: https://acme-staging-v02.api.letsencrypt.org/directory
account_key: config/account-staging.key
key_length: 4096
acme_dir: /media/acme-challenge
certs:
  - name: example.com
    domains:
      - example.com
      - www.example.com
